
# 1. Tomcat Server Setting
server:
  port: 85
  servlet:
    encoding:
      charset: UTF-8
      force: true

# 2. SpringBoot Environment Setting
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://210.119.34.205:3306/final_db?characterEncoding=utf8
    # JDBC URL 변경 시 주석 해제하여 사용
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://127.0.0.1:3306/smdb?characterEncoding=utf8
    username: ENC(OAjB56HlNziHqNDu8ZFSAw==)
    password: ENC(zYoWFnp8CokAEj/HgST7Tw==)
#    # MIME 타입 설정 추가
#    servlet:
#      context-parameters:
#        "com.sun.jersey.api.json.POJOMappingFeature": "true"
#      mapping:
#        "application/javascript": ".js"

# 3. Mybatis Setting
mybatis:
  type-aliases-package: edu.sm.app.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
# 4. Logging Setting
logging:
  level:
    root: info
  #  error > info > debug

# 5. Application Environment Setting
app:
  url:
    server-url: http://210.119.34.194:84
    # 관리자와 대화이므로 관리자 ip:포트로 설정.
  dir:
      # 이미지 업로드 디렉토리 경로
    uploadimgdir: c:/SMGym/imgs/
      # 이미지 파일을 서빙할 경로 (Spring Boot에서 정적 리소스 제공)
    imgdir: file:///c:/SMGym/imgs/
      # 로그 디렉토리 경로
    logdir: file:///c:/SMGym/SMGym/logs/
    readlogdir: c:/SMGym/SMGym/logs/

  key:
    wkey: ENC(kZ7Yfw4X1FM0QoaT2JmRt6kwvym87T1XWJElWSSOdr8cWTt9F4jvIYDSg0ln0yRnaok3xpgvoxnasT6j2AwbYrefa0WzBj01wVM2bffER3Oz/ZgJaHzHsOqVNzSd4X/vgww4gPCvO0MY/uHKWcahQA==)
    wkey2: ENC(IaCxGmepCY1Whp5Er+hrlSw/x8KHH27jDlPonPGZq+FBPK6QzzXBY+ydg+ti50XN)
    algo: PBEWithMD5AndDES #알고리즘에 따라서 해당 평문에대한 암호화를 결정할 수 있다.
    skey: mykey

    naver:
      request-token-uri: https://nid.naver.com/oauth2.0/token
      client-id: aw1RRWvVpiActYPMafa9
      client-secret: UEgAxv_E_z

iamport:
  apiKey: 6178544642102448
  apiSecret: CyhPLOBsAMQCguuhiUjYuD3d1ABO85mVM9t3Fq67JTlKIKcgeInMqh9MqnWWYHHjrRD60Vle4UALHzSn

