# 1. Tomcat Server Setting
server:
  port: 84
  servlet:
    encoding:
      charset: UTF-8
      force: true

# 2. SpringBoot Environment Setting
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://210.119.34.205:3306/final_db?characterEncoding=utf8
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/smdb?characterEncoding=utf8
    username: ENC(fGsN6SwFRd3uGcmdRmsGCw==)
    password: ENC(9InL1LFs0co8Hug4cT2/2A==)

# 3. Mybatis Setting
mybatis:
  type-aliases-package: edu.sm.app.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
# 4. Logging Setting
logging:
  level:
    root: info
    edu.sm: DEBUG
  #  error > info > debug

# 5. Application Environment Setting
app:
  url:
    server-url: http://210.119.34.194:84
  dir:
    uploadimgdir: c:/springsm/springsm/imgs/
    imgdir: file:///c:/springsm/springsm/imgs/
    #java밑에 config 밑에 webMvcConfig때문에 사용 이 폴더의 정보를 가져오기위해 사용
    # logdir: /root/users/project/logs
    logdir: file:///c:/springsm/springsm/logs/
    readlogdir: c:/springsm/springsm/logs/
  key:
    wkey: ENC(kZ7Yfw4X1FM0QoaT2JmRt6kwvym87T1XWJElWSSOdr8cWTt9F4jvIYDSg0ln0yRnaok3xpgvoxnasT6j2AwbYrefa0WzBj01wVM2bffER3Oz/ZgJaHzHsOqVNzSd4X/vgww4gPCvO0MY/uHKWcahQA==)
    wkey2: ENC(IaCxGmepCY1Whp5Er+hrlSw/x8KHH27jDlPonPGZq+FBPK6QzzXBY+ydg+ti50XN)
    algo: PBEWithMD5AndDES
    skey: mykey
